version: "3.3"

services:
  grpc-server:
    container_name: grpc-server
    build:
      context: . #./grpc-server
      dockerfile: grpc-server/Dockerfile
    ports:
      - "50051:50051"
    networks:
      - project-network

  http-api:
    container_name: http-api
    build:
      context: . #./http-api
      dockerfile: http-api/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - grpc-server
    environment:
      GRPC_HOST: grpc-server
      GRPC_PORT: 50051
    networks:
      - project-network

networks:
  project-network:
    driver: bridge