{
 "title": "Alertas de Seguridad",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Alertas totales",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSQL": "SELECT COUNT(*) AS total_alerts FROM security_alerts",
     "rawSql": "SELECT COUNT(*) AS \"total_alerts\" FROM security_alerts"
    }
   ]
  },
  {
   "title": "Tipo de alertas",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSQL": "SELECT alert_type, COUNT(*) FROM security_alerts GROUP BY alert_type",
     "rawSql": "SELECT alert_type, COUNT(*) AS \"total_alerts\" FROM security_alerts GROUP BY alert_type;"
    }
   ]
  },
  {
   "title": "Tipo de severidad - out-of-distribution",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT severity, COUNT(*) FROM ood_alerts GROUP BY severity;"
    }
   ]
  },
  {
   "title": "Alertas por Feature",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSQL": "SELECT feature, COUNT(*) FROM security_alerts GROUP BY feature",
     "rawSql": "SELECT feature, COUNT(*) FROM security_alerts WHERE feature <> 'ALL_FEATURES' GROUP BY feature;"
    }
   ]
  }
 ]
}