[tool.poetry]
name = "grpc-server"
version = "0.1.0"
description = ""
authors = ["Gaspar Acevedo Zain", "Gaspar Acevedo"]
readme = "README.md"
packages = [{ include = "grpc-server", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
grpcio = "^1.50.0"
grpcio-tools = "^1.50.0"
scikit-learn = "^1.0.0"

[tool.poetry.group.dev.dependencies]
black = "^24.3.0"
flake8 = "^7.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
