[tool.poetry]
name = "wine-trainer"
version = "0.1.0"
description = "Trainer para Wine Classification con MLflow"
authors = ["Gaspar Acevedo Zain", "Jonathan Borda", "Carlos Villalobos"]
packages = [{ include = "wine_trainer", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.26"
pandas = "^2.2"
scikit-learn = "^1.4"
mlflow = "^3.10.1"
pydantic = "^2.6"
boto3 = "^1.42.82"

[tool.poetry.group.dev.dependencies]
black = "^24.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"