[tool.poetry]
name = "http-api"
version = "0.1.0"
description = "Cliente FastAPI para servidor gRPC ML"
authors = ["Gaspar Acevedo Zain", "Gaspar Acevedo"]
readme = "README.md"
packages = [{ include = "http_api", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.110.0"
uvicorn = "^0.27.1"
grpcio = "^1.62.0"
protobuf = "^6.31.1"
pydantic = "^2.6.3"

[tool.poetry.group.dev.dependencies]
black = "^24.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"