FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl build-essential \
    && rm -rf /var/lib/apt/lists/*

ENV POETRY_VERSION=1.8.3
RUN curl -sSL https://install.python-poetry.org | python3 - && \
    ln -s /root/.local/bin/poetry /usr/local/bin/poetry

WORKDIR /app

COPY ./pyproject.toml /app/
COPY ./poetry.lock /app/
RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi --only main

COPY ./src /app/src
COPY ./main.py /app/