[tool.poetry]
name = "graphql-api"
version = "0.1.0"
description = ""
authors = ["Gaspar Acevedo Zain", "Gaspar Acevedo"]
readme = "README.md"
packages = [{ include = "graphql-api", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.100.0"
uvicorn = {extras = ["standard"], version = "^0.23.2"}
strawberry-graphql = {extras = ["fastapi"], version = "^0.200.0"}
scikit-learn = "^1.0.0"

[tool.poetry.group.dev.dependencies]
black = "^24.3.0"
flake8 = "^7.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
